matrix:
  include:
    - os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
before_script:
  - git lfs pull

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "yarn --link-duplicates --pure-lockfile && yarn release --linux --win"
    else
      yarn release
    fi
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  api_key:
    secure: PkW9NrqzBsjbtTbI0YkVn4/Ni1pDCHDisEKjxeYhjTm5VF3nY7JXTP6lVUH45H40CtcXSgF+ar0Ob4prMYfXJxtMgv3wdnvaSn/SRIdnWkY2w5WXW75ys3rlRwan9G6jpysYayxnPWYjFootHNdoxVhkQzQOnzMFYocT0gJkbCdcbHWGLx1irqOBa9enicqjjBDV2mBo+NHjlHXnMOhTO9+x7oe0uQFC/DWtlwGMc5xj+1n/4SA+pWmr8JQfuFGOdyVgaKYY+BdLSGzkUK6pQqmGwPmYpHPSNnNggRWXXacI10miDfAigrA9rfWdjL2yDpjOu0I/eNDElMjSbhj8x/EvEDY5Ptqi+lZz5rE5fioApiG6FQoZiqQHTP7/T0JLBSqGUVwf+TYD/IaCVh8JMBkgpi9ujM9Dqopz9nhxNFEaiano8chC9/1+rO/9TfyKtu41brAYDZZMM0DxLkS5STNYwAECQi7HVW5DQCxxKzz14MhBGuU4XsACH+qUxcUtvywlQH0OdDWhvw6oAg+P5mmpPy/GHkmZsaTiVPatZQwpbV4R5P+x706ArLauWcxaOL/cye6X0fjWyLlvJbyE722gyRwR1uLgYeW2e+RSIcPzgrpCijwkzNHdeExprwGR7z+k1xP2B05UA/6HlBa5SRBvXsA8yEVYTgtY649fbto=
  file:
    - 'release-builds/mac-osx.tar.gz'
    - 'release-builds/linux-x64.tar.gz'
    #- 'release-builds/win32.tar.gz'
  skip_cleanup: true
  on:
    repo: idees/idees
    branch: master